# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MidPoint
                                 A QGIS plugin
 The plugin find the central vertex and it generates a point in the middle of the line segment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-12
        copyright            : (C) 2023 by Sergi Alvarez Guasch
        email                : sergiguasch83@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MidPoint class from file MidPoint.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mid_point import MidPoint
    return MidPoint(iface)
