# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sergi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mid_point\mid_point_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MidPointDialogBase(object):
    def setupUi(self, MidPointDialogBase):
        MidPointDialogBase.setObjectName("MidPointDialogBase")
        MidPointDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(MidPointDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.layerCombo = QtWidgets.QComboBox(MidPointDialogBase)
        self.layerCombo.setGeometry(QtCore.QRect(50, 80, 281, 20))
        self.layerCombo.setObjectName("layerCombo")

        self.retranslateUi(MidPointDialogBase)
        self.button_box.accepted.connect(MidPointDialogBase.accept)
        self.button_box.rejected.connect(MidPointDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MidPointDialogBase)

    def retranslateUi(self, MidPointDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MidPointDialogBase.setWindowTitle(_translate("MidPointDialogBase", "Mid Point"))
